-- MySQL Script generated by MySQL Workbench
-- Mon Mar 26 16:35:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema polaris
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema polaris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `polaris` DEFAULT CHARACTER SET utf8 ;
USE `polaris` ;

-- -----------------------------------------------------
-- Table `polaris`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `polaris`.`agent` (
  `id` VARCHAR(36) NOT NULL COMMENT 'agent id',
  `alias` VARCHAR(45) NULL COMMENT 'agent别名，一般为hostname',
  `ip` BLOB NULL COMMENT 'agent监听的ip地址，json字符串: [“121.41.41.54”, “10.0.1.8”]',
  `offline` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否离线，0：离线 1：在线',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标识',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用，1：启动；0：禁用',
  `ctime` BIGINT(13) NULL COMMENT '创建时间，为agent首次注册时间',
  `mtime` BIGINT(13) NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `polaris`.`instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `polaris`.`instance` (
  `id` VARCHAR(36) NOT NULL,
  `sn` VARCHAR(36) NULL COMMENT '服务实例编号',
  `agent_id` VARCHAR(36) NULL,
  `service_id` VARCHAR(36) NULL,
  `listen_ip` VARCHAR(16) NULL COMMENT '监听的ip地址',
  `listen_port` INT NULL COMMENT '监听端口',
  `ctime` BIGINT(13) NULL COMMENT '创建时间',
  `mtime` BIGINT(13) NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `polaris`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `polaris`.`service` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '服务集群名称',
  `remark` VARCHAR(128) NULL COMMENT '服务集群备注',
  `ctime` BIGINT(13) NULL,
  `mtime` BIGINT(13) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `polaris`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `polaris`.`task` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NULL,
  `begin` BIGINT(16) NULL,
  `end` BIGINT(16) NULL,
  `service_id` VARCHAR(36) NULL,
  `service_name` VARCHAR(45) NULL,
  `details` BLOB NULL,
  `ctime` BIGINT(13) NULL,
  `mtime` BIGINT(13) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `polaris`.`task_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `polaris`.`task_log` (
  `id` INT NOT NULL,
  `task_id` VARCHAR(45) NULL,
  `instance_id` VARCHAR(45) NULL,
  `log` BLOB NULL,
  `ctime` BIGINT(13) NULL,
  `mtime` BIGINT(13) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
